#!/bin/bash
. /usr/bin/aops-utils

CHECK_SCHEDULER_CONSTANT="adoctor-check-scheduler"
CHECK_SCHEDULER_CONFIG_FILE=$SYS_PATH/check_scheduler.ini

function main() {
  if [ "${OPERATION}" = "start" ]; then
    create_config_file "${CHECK_SCHEDULER_CONFIG_FILE}" "check_scheduler" "adoctor"
  fi
  start_or_stop_service "${CHECK_SCHEDULER_CONSTANT}"
}

main
