class ANOMALY_DETECTION_MODEL_TYPE:
    EXPERT_MODEL = "EXPERT_MODEL"
    AI_MODEL = "AI_MODEL"

class ATTR_ANOMALY_TYPE:
    BELOW_THRESHOLD = "BELOW THRESHOLD"
    ABOVE_THRESHOLD = "ABOVE THRESHOLD"

class OBJECT_TYPE:
    TCP_LINK = "tcp_link"
    NODES = "nodes"
    LB = "lb"
    VM = "vm"

class ANOMALY_STATUS:
    ANOMALY_NO = "ANOMALY_NO"
    ANOMALY_YES = "ANOMALY_YES"
    ANOMALY_LACKING = "ANOMALY_LACKING"

g_edges_list = {"timestamp": 0, OBJECT_TYPE.TCP_LINK: {}}
EDGES_LIST_UPDATE_INTERVAL = 20