#!/bin/bash
. /usr/bin/aops-utils

DIAG_SCHEDULER_CONSTANT="adoctor-diag-scheduler"
DIAG_SCHEDULER_CONFIG_FILE=$SYS_PATH/diag_scheduler.ini

function main() {
  if [ "${OPERATION}" = "start" ]; then
    create_config_file "${DIAG_SCHEDULER_CONFIG_FILE}" "diag_scheduler" "adoctor"
  fi
  start_or_stop_service "${DIAG_SCHEDULER_CONSTANT}"
}

main
