# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util


class ConfFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, file_path: str=None, contents: str=None):  # noqa: E501
        """ConfFile - a model defined in Swagger

        :param file_path: The file_path of this ConfFile.  # noqa: E501
        :type file_path: str
        :param contents: The contents of this ConfFile.  # noqa: E501
        :type contents: str
        """
        self.swagger_types = {
            'file_path': str,
            'contents': str
        }

        self.attribute_map = {
            'file_path': 'filePath',
            'contents': 'contents'
        }

        self._file_path = file_path
        self._contents = contents

    @classmethod
    def from_dict(cls, dikt) -> 'ConfFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfFile of this ConfFile.  # noqa: E501
        :rtype: ConfFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_path(self) -> str:
        """Gets the file_path of this ConfFile.

        the path of a configuration file  # noqa: E501

        :return: The file_path of this ConfFile.
        :rtype: str
        """
        return self._file_path

    @file_path.setter
    def file_path(self, file_path: str):
        """Sets the file_path of this ConfFile.

        the path of a configuration file  # noqa: E501

        :param file_path: The file_path of this ConfFile.
        :type file_path: str
        """

        self._file_path = file_path

    @property
    def contents(self) -> str:
        """Gets the contents of this ConfFile.

        the contents of the configuration file  # noqa: E501

        :return: The contents of this ConfFile.
        :rtype: str
        """
        return self._contents

    @contents.setter
    def contents(self, contents: str):
        """Sets the contents of this ConfFile.

        the contents of the configuration file  # noqa: E501

        :param contents: The contents of this ConfFile.
        :type contents: str
        """

        self._contents = contents
