# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util


class Domain(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, domain_name: str=None, priority: int=None):  # noqa: E501
        """Domain - a model defined in Swagger

        :param domain_name: The domain_name of this Domain.  # noqa: E501
        :type domain_name: str
        :param priority: The priority of this Domain.  # noqa: E501
        :type priority: int
        """
        self.swagger_types = {
            'domain_name': str,
            'priority': int
        }

        self.attribute_map = {
            'domain_name': 'domainName',
            'priority': 'priority'
        }

        self._domain_name = domain_name
        self._priority = priority

    @classmethod
    def from_dict(cls, dikt) -> 'Domain':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Domain of this Domain.  # noqa: E501
        :rtype: Domain
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_name(self) -> str:
        """Gets the domain_name of this Domain.

        domain name  # noqa: E501

        :return: The domain_name of this Domain.
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name: str):
        """Sets the domain_name of this Domain.

        domain name  # noqa: E501

        :param domain_name: The domain_name of this Domain.
        :type domain_name: str
        """

        self._domain_name = domain_name

    @property
    def priority(self) -> int:
        """Gets the priority of this Domain.

        Priority of the current domain  # noqa: E501

        :return: The priority of this Domain.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this Domain.

        Priority of the current domain  # noqa: E501

        :param priority: The priority of this Domain.
        :type priority: int
        """

        self._priority = priority
