# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util
from ragdoll.models.path import Path


class ExpectedConf(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, domain_name: str=None, paths: List[Path]=None):  # noqa: E501
        """ExpectedConf - a model defined in Swagger

        :param domain_name: The domain_name of this ExpectedConf.  # noqa: E501
        :type domain_name: str
        :param paths: The paths of this ExpectedConf.  # noqa: E501
        :type paths: List[Path]
        """
        self.swagger_types = {
            'domain_name': str,
            'paths': List[Path]
        }

        self.attribute_map = {
            'domain_name': 'domainName',
            'paths': 'paths'
        }

        self._domain_name = domain_name
        self._paths = paths

    @classmethod
    def from_dict(cls, dikt) -> 'ExpectedConf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExpectedConf of this ExpectedConf.  # noqa: E501
        :rtype: ExpectedConf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_name(self) -> str:
        """Gets the domain_name of this ExpectedConf.


        :return: The domain_name of this ExpectedConf.
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name: str):
        """Sets the domain_name of this ExpectedConf.


        :param domain_name: The domain_name of this ExpectedConf.
        :type domain_name: str
        """

        self._domain_name = domain_name

    @property
    def paths(self) -> List[Path]:
        """Gets the paths of this ExpectedConf.


        :return: The paths of this ExpectedConf.
        :rtype: List[Path]
        """
        return self._paths

    @paths.setter
    def paths(self, paths: List[Path]):
        """Sets the paths of this ExpectedConf.


        :param paths: The paths of this ExpectedConf.
        :type paths: List[Path]
        """

        self._paths = paths
