# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util
from ragdoll.models.host import Host


class HostInfos(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, domain_name: str=None, host_infos: List[Host]=None):  # noqa: E501
        """HostInfos - a model defined in Swagger

        :param domain_name: The domain_name of this HostInfos.  # noqa: E501
        :type domain_name: str
        :param host_infos: The host_infos of this HostInfos.  # noqa: E501
        :type host_infos: List[Host]
        """
        self.swagger_types = {
            'domain_name': str,
            'host_infos': List[Host]
        }

        self.attribute_map = {
            'domain_name': 'domainName',
            'host_infos': 'hostInfos'
        }

        self._domain_name = domain_name
        self._host_infos = host_infos

    @classmethod
    def from_dict(cls, dikt) -> 'HostInfos':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HostInfos of this HostInfos.  # noqa: E501
        :rtype: HostInfos
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_name(self) -> str:
        """Gets the domain_name of this HostInfos.

        domain name  # noqa: E501

        :return: The domain_name of this HostInfos.
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name: str):
        """Sets the domain_name of this HostInfos.

        domain name  # noqa: E501

        :param domain_name: The domain_name of this HostInfos.
        :type domain_name: str
        """

        self._domain_name = domain_name

    @property
    def host_infos(self) -> List[Host]:
        """Gets the host_infos of this HostInfos.


        :return: The host_infos of this HostInfos.
        :rtype: List[Host]
        """
        return self._host_infos

    @host_infos.setter
    def host_infos(self, host_infos: List[Host]):
        """Sets the host_infos of this HostInfos.


        :param host_infos: The host_infos of this HostInfos.
        :type host_infos: List[Host]
        """

        self._host_infos = host_infos
