# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util


class ManageConf(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, file_path: str=None):  # noqa: E501
        """ManageConf - a model defined in Swagger

        :param file_path: The file_path of this ManageConf.  # noqa: E501
        :type file_path: str
        """
        self.swagger_types = {
            'file_path': str
        }

        self.attribute_map = {
            'file_path': 'filePath'
        }

        self._file_path = file_path

    @classmethod
    def from_dict(cls, dikt) -> 'ManageConf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ManageConf of this ManageConf.  # noqa: E501
        :rtype: ManageConf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_path(self) -> str:
        """Gets the file_path of this ManageConf.

        the path of a configuration file  # noqa: E501

        :return: The file_path of this ManageConf.
        :rtype: str
        """
        return self._file_path

    @file_path.setter
    def file_path(self, file_path: str):
        """Sets the file_path of this ManageConf.

        the path of a configuration file  # noqa: E501

        :param file_path: The file_path of this ManageConf.
        :type file_path: str
        """

        self._file_path = file_path
