# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util


class Path(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, path: str=None):  # noqa: E501
        """Path - a model defined in Swagger

        :param path: The path of this Path.  # noqa: E501
        :type path: str
        """
        self.swagger_types = {
            'path': str
        }

        self.attribute_map = {
            'path': 'path'
        }

        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'Path':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Path of this Path.  # noqa: E501
        :rtype: Path
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self) -> str:
        """Gets the path of this Path.

        the configuration items path of a xpath  # noqa: E501

        :return: The path of this Path.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this Path.

        the configuration items path of a xpath  # noqa: E501

        :param path: The path of this Path.
        :type path: str
        """

        self._path = path
