# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util
from ragdoll.models.realconf_base_info import RealconfBaseInfo


class RealConfInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, domain_name: str=None, host_id: str=None, conf_base_infos: List[RealconfBaseInfo]=None):  # noqa: E501
        """RealConfInfo - a model defined in Swagger

        :param domain_name: The domain_name of this RealConfInfo.  # noqa: E501
        :type domain_name: str
        :param host_id: The host_id of this RealConfInfo.  # noqa: E501
        :type host_id: str
        :param conf_base_infos: The conf_base_infos of this RealConfInfo.  # noqa: E501
        :type conf_base_infos: List[RealconfBaseInfo]
        """
        self.swagger_types = {
            'domain_name': str,
            'host_id': str,
            'conf_base_infos': List[RealconfBaseInfo]
        }

        self.attribute_map = {
            'domain_name': 'domainName',
            'host_id': 'hostID',
            'conf_base_infos': 'confBaseInfos'
        }

        self._domain_name = domain_name
        self._host_id = host_id
        self._conf_base_infos = conf_base_infos

    @classmethod
    def from_dict(cls, dikt) -> 'RealConfInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RealConfInfo of this RealConfInfo.  # noqa: E501
        :rtype: RealConfInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_name(self) -> str:
        """Gets the domain_name of this RealConfInfo.


        :return: The domain_name of this RealConfInfo.
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name: str):
        """Sets the domain_name of this RealConfInfo.


        :param domain_name: The domain_name of this RealConfInfo.
        :type domain_name: str
        """

        self._domain_name = domain_name

    @property
    def host_id(self) -> str:
        """Gets the host_id of this RealConfInfo.


        :return: The host_id of this RealConfInfo.
        :rtype: str
        """
        return self._host_id

    @host_id.setter
    def host_id(self, host_id: str):
        """Sets the host_id of this RealConfInfo.


        :param host_id: The host_id of this RealConfInfo.
        :type host_id: str
        """

        self._host_id = host_id

    @property
    def conf_base_infos(self) -> List[RealconfBaseInfo]:
        """Gets the conf_base_infos of this RealConfInfo.


        :return: The conf_base_infos of this RealConfInfo.
        :rtype: List[RealconfBaseInfo]
        """
        return self._conf_base_infos

    @conf_base_infos.setter
    def conf_base_infos(self, conf_base_infos: List[RealconfBaseInfo]):
        """Sets the conf_base_infos of this RealConfInfo.


        :param conf_base_infos: The conf_base_infos of this RealConfInfo.
        :type conf_base_infos: List[RealconfBaseInfo]
        """

        self._conf_base_infos = conf_base_infos
