# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util
from ragdoll.models.real_conf import RealConf


class RealConfPath(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, domain_name: str=None, host_id: str=None, real_conf: List[RealConf]=None):  # noqa: E501
        """RealConfPath - a model defined in Swagger

        :param domain_name: The domain_name of this RealConfPath.  # noqa: E501
        :type domain_name: str
        :param host_id: The host_id of this RealConfPath.  # noqa: E501
        :type host_id: str
        :param real_conf: The real_conf of this RealConfPath.  # noqa: E501
        :type real_conf: List[RealConf]
        """
        self.swagger_types = {
            'domain_name': str,
            'host_id': str,
            'real_conf': List[RealConf]
        }

        self.attribute_map = {
            'domain_name': 'domainName',
            'host_id': 'hostId',
            'real_conf': 'realConf'
        }

        self._domain_name = domain_name
        self._host_id = host_id
        self._real_conf = real_conf

    @classmethod
    def from_dict(cls, dikt) -> 'RealConfPath':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RealConfPath of this RealConfPath.  # noqa: E501
        :rtype: RealConfPath
        """
        return util.deserialize_model(dikt, cls)

    @property
    def domain_name(self) -> str:
        """Gets the domain_name of this RealConfPath.


        :return: The domain_name of this RealConfPath.
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name: str):
        """Sets the domain_name of this RealConfPath.


        :param domain_name: The domain_name of this RealConfPath.
        :type domain_name: str
        """

        self._domain_name = domain_name

    @property
    def host_id(self) -> str:
        """Gets the host_id of this RealConfPath.


        :return: The host_id of this RealConfPath.
        :rtype: str
        """
        return self._host_id

    @host_id.setter
    def host_id(self, host_id: str):
        """Sets the host_id of this RealConfPath.


        :param host_id: The host_id of this RealConfPath.
        :type host_id: str
        """

        self._host_id = host_id

    @property
    def real_conf(self) -> List[RealConf]:
        """Gets the real_conf of this RealConfPath.


        :return: The real_conf of this RealConfPath.
        :rtype: List[RealConf]
        """
        return self._real_conf

    @real_conf.setter
    def real_conf(self, real_conf: List[RealConf]):
        """Sets the real_conf of this RealConfPath.


        :param real_conf: The real_conf of this RealConfPath.
        :type real_conf: List[RealConf]
        """

        self._real_conf = real_conf
