# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ragdoll.models.base_model_ import Model
from ragdoll import util


class SyncHostConfs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, host_id: int = None, sync_configs: List[str] = None):  # noqa: E501
        """ConfHost - a model defined in Swagger

        :param domain_name: The domain_name of this ConfHost.  # noqa: E501
        :type domain_name: str
        :param host_ids: The host_ids of this ConfHost.  # noqa: E501
        :type host_ids: List[object]
        """
        self.swagger_types = {
            'host_id': int,
            'sync_configs': List[str]
        }

        self.attribute_map = {
            'host_id': 'hostId',
            'sync_configs': 'syncConfigs'
        }

        self._host_id = host_id
        self._sync_configs = sync_configs

    @classmethod
    def from_dict(cls, dikt) -> 'SyncHostConfs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfHost of this ConfHost.  # noqa: E501
        :rtype: ConfHost
        """
        return util.deserialize_model(dikt, cls)

    @property
    def host_id(self) -> int:
        """Gets the domain_name of this ConfHost.

        domain name  # noqa: E501

        :return: The domain_name of this ConfHost.
        :rtype: str
        """
        return self._host_id

    @host_id.setter
    def host_id(self, host_id: int):
        """Sets the domain_name of this ConfHost.

        domain name  # noqa: E501

        :param host_id: The domain_name of this ConfHost.
        :type host_id: int
        """

        self._host_id = host_id

    @property
    def sync_configs(self) -> List[str]:
        """Gets the host_ids of this ConfHost.


        :return: The host_ids of this ConfHost.
        :rtype: List[str]
        """

        return self._sync_configs

    @sync_configs.setter
    def sync_configs(self, sync_configs: List[str]):
        """Sets the host_ids of this ConfHost.


        :param sync_configs: The host_ids of this ConfHost.
        :type sync_configs: List[str]
        """

        self._sync_configs = sync_configs
