#!/bin/bash
. /usr/bin/aops-utils

MANAGER_CONSTANT="aops-manager"
MANAGER_CONFIG_FILE=$SYS_PATH/manager.ini

function main() {
  if [ "${OPERATION}" = "start" ]; then
    create_config_file "${MANAGER_CONFIG_FILE}" "manager" "aops"
    check_mysql_installed "${MANAGER_CONFIG_FILE}"
    check_es_installed "${MANAGER_CONFIG_FILE}"
  fi
  start_or_stop_service "${MANAGER_CONSTANT}"
  exit $?
}

main
