# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from spider.models.base_model_ import Model
from spider import util


class Attr(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, key: str=None, value: str=None, vtype: str=None):  # noqa: E501
        """Attr - a model defined in Swagger

        :param key: The key of this Attr.  # noqa: E501
        :type key: str
        :param value: The value of this Attr.  # noqa: E501
        :type value: str
        :param vtype: The vtype of this Attr.  # noqa: E501
        :type vtype: str
        """
        self.swagger_types = {
            'key': str,
            'value': str,
            'vtype': str
        }

        self.attribute_map = {
            'key': 'key',
            'value': 'value',
            'vtype': 'vtype'
        }

        self._key = key
        self._value = value
        self._vtype = vtype

    @classmethod
    def from_dict(cls, dikt) -> 'Attr':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Attr of this Attr.  # noqa: E501
        :rtype: Attr
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this Attr.


        :return: The key of this Attr.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this Attr.


        :param key: The key of this Attr.
        :type key: str
        """

        self._key = key

    @property
    def value(self) -> str:
        """Gets the value of this Attr.


        :return: The value of this Attr.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this Attr.


        :param value: The value of this Attr.
        :type value: str
        """

        self._value = value

    @property
    def vtype(self) -> str:
        """Gets the vtype of this Attr.


        :return: The vtype of this Attr.
        :rtype: str
        """
        return self._vtype

    @vtype.setter
    def vtype(self, vtype: str):
        """Sets the vtype of this Attr.


        :param vtype: The vtype of this Attr.
        :type vtype: str
        """
        allowed_values = ["int", "string", "float"]  # noqa: E501
        if vtype not in allowed_values:
            raise ValueError(
                "Invalid value for `vtype` ({0}), must be one of {1}"
                .format(vtype, allowed_values)
            )

        self._vtype = vtype
